version: '3.8'

services:
  airflow:
    build: 
      context: .
    ports:
     - "8080:8080"
    environment:
     - AIRFLOW_HOME=/opt/airflow
    volumes:
     - ./dags:/opt/airflow/dags
     - ./pipelines:/opt/airflow/pipelines
     - ./data:/opt/airflow/data
    
    command: ["airflow", "standalone"]
